### ISSUE TITLE
Explaining the coefficients in say csmBlades.py file

### ISSUE THREAD

**Issue by anuactwind** [WISDEM/NREL_CSM#1]
As in any other file the csmBlades.py has codes that are based on NREL 2006 scaling model. These codes consist of the coefficients such as 

```
massCoeff = 0.4948      line 68
massExp   = 2.5300       line 69
```
       ****or****
```
slopeR3   = 0.4019376            line 100
intR3     = -21051.045983        line 101
```

These coefficients are derived from data exclusive to NREL and US market. 

Any suggestion on generating or finding the coefficients that suit other markets and countries? Rather unlikely, but can the same cost model be used in other parts of the world?

**Comment by dykesk** [comment]
The model was developed a long time ago now (between 2001 - 2005) and was based on the technology of the time and the US market.  So, caution should be exercised in using the model to represent current technology.  To adapt to other markets, you could just take the final result and do a currency exchange; or do it for each individual component if you wanted.

**Comment by anuactwind** [comment]
Thank you, Katherine. I was wondering if you could provide your insights on how I can use the cost model to determine any barriers in technology that may restrict scaling of the turbines or its components? I mean how would I integrate and analyse the results with the learning curves? Is it the proper way to go? Thank you again.

**Comment by dykesk** [comment]
I wouldn't use this model for that purpose.  It's based on design studies from the early 2000s and technology of that time - so the scaling laws that are in the model are no longer relevant.  If you look to the new WISDEM model, we are going to publish new scaling laws soon based on current technology.  Regarding the general approach, i think it is challenging to use these scaling laws to push much far beyond the current data from which they are derived.  There is a lot of complexity in the physics of wind turbines.  It sounds like what you have here is more of a research question than software so I recommend you contact me directly so I have more context for what you are trying to do.

**Comment by SamAct** [comment]
Thank you for the reply. I am aware that the cost model is a bit irrelevant as the technology has changed since 2002. I am trying to improve on the cost model as per the modern context. The plan is to have a Python application, with the relations improved for both baseline and advanced scenarios.

In the model, the capacity factor is a user input variable but I think it would be better to derive it based on a hypothetical plant layout and wind data. This could be changed when required.

With the aim to calculate the cost of energy and plotting it with the capacity factor to determine how the capacity factor vary with the change in the COE for any two different turbines say.

At present, I am starting out with the Algorithm and determining the relations between the components. I am sure I can derive better relations for mass and cost for the Rotor section (Blades, hub etc) but obtaining the relations for Drivetrain or the tower seems challenging.

I would like to discuss further with you on how I can validate my relations and more importantly how to get them properly. I understand it's a huge research but since the model will be for a local market with max of 2  or 3 MW machines we can loosen it a bit. Please tell me the best way to contact you and go forward with this.

Thank you again for you help.

**Comment by SamAct** [comment]
One more issue I would like to add is the frequency of electrical supply. In the USA, all generators would have been designed to produce an output frequency of 60HZ, if we are changing this, it will effect the weight and loads of the generator, is there a way around this when scaling the model?

**Comment by dykesk** [comment]
The cost model that we maintain is in the official WISDEM model set - the cost model has been broken out and updated in the constituent components.  There is a new balance of station model, turbine cost model, etc.  You can find the different subsystem models in each of the SE models.  These aggregate up into WISDEM assemblies.  Please see the other models on the organization and their associated documentation.  I will likely delete this repository to avoid confusion like this in the future. 

The NREL_CSM model is not used at all.  Newer models have replaced it.

**Comment by SamAct** [comment]
I hope I am clear, the CSM model is based on the DEC 2006 release based on NREl work on Sunderland Model and WISDEM is the improved version of the model. But scaling model for WISDEM has not yet been published but due soon!!

**Comment by dykesk** [comment]
Yes - this is mostly the case.  some of the models are already published; you can find them on the develop branches of the the model repositories.  The parts that are update include the turbine sizing and cost and the balance of station.  The operations and maintenance model will be updated in the future.  The aep model is the same but you can also use more complex wind plant models.  You will need to read the documentation for each SE model to understand better the capabilities.

**Comment by SamAct** [comment]
Yes thank you I shall keep you posted.
