### ISSUE TITLE
Cost of Wind energy reviews

### ISSUE THREAD

**Issue by dali-dali** [WISDEM/NREL_CSM#4]
Dear Katherine, 

I am Dali - a PhD student in economics from CERGE-EI -  a U.S. chartered program in Czech Republic. I am doing my research in the renewable energy sector, in particular, wind and solar energy.

I am analyzing NREL's Cost of Wind Energy Reviews and I am trying to replicate all the wind turbine cost components NREL documents in these reports. In the earlier versions 2010-2011 I succeed in replicating most of the costs using Fingersh 2006 model, while this is not the case in later reports...

I recently discovered your softwares like NREL_CSM and WISDEM and was wondering which software did you use to calculate the component costs in "Cost of Wind energy review"-s 2010-2015?

Your answer will rescue me, because I had already lost the hope that I will be able to replicate the results...

**Comment by dykesk** [comment]
Hello Dali,

 

You are correct.  We have moved away from using the Fingersh 2006 model in the last few years.  In the past few years, we have used a combination of the Fingersh model along with new market data.  Unfortunately, there is not a published model that we directly used in those reports since a lot of it was done using internal data.

 

NREL_CSM is a direct implementation of Fingersh 2006 in Python.

 

WISDEM’s Turbine_CostsSE includes the Fingersh 2006 model and an updated model with 2015 data that is still under development and has not been published.  That model is in OpenMDAO (which also uses python).  I expect we will publish a report here in 2017 on a new model to replace the Fingersh model and that model will be used going forward in the Cost of Wind Energy review studies.

 

Sorry that I cannot provide more help at this time.  Look later this year for the update report and model, or you can use the report data directly in your analysis if that is possible, since that represents the more recent market cost trends in the US.  Also see the IEA Wind Cost of Wind Energy reports as well as they represent a more global look at wind cost of energy.

 

Kind regards, - Katherine

**Comment by dali-dali** [comment]
Thank you, Katherine for this helpful e-mail, because it is signaling me
that it might be a good time to switch to another approach, even though I
have invested in this pretty valuable time....
So,  " In the past few years, we have used a combination of the Fingersh
model along with new market data" - this means that some of the cost
components were not coming from any model but was just market data, right?

Unfortunately, I cannot just use the reported numbers from "cost of wind
energy reviews" because I am exploring the drivers of cost reduction. For
example, in years 2010-2012 apparently, the drivers of cost changes were
larger turbines and rotor diameter.

But what happened next? Was it that old generators were replaced with more
efficient generators? The baseline blades were replaced with advanced ones?
the manufacturers switched from geared generators to non-geared? New
methods of transportation discovered?  - I need to know exactly what
happened in order to evaluate the cost reduction and policy impacts...

The "cost of wind energy reviews" are not detailed about such changes - if
it was, the reported numbers could suffice...

I don't know if you could help me with this but you can help me in one
thing, could you advise me the reports, papers or books were these
technological changes are coherently documented in recent years? The more
sources, the better :)

Best!

**Comment by dykesk** [comment]
Hi Dali - these are good questions but they are not software related.  Please email systems.engineering@nrel.gov and we can continue the dialogue.  i'm going to close this issue on github since it is not software related.
